### ISSUE TITLE
Something wrong when implementing

### ISSUE THREAD

**Issue by HappyGu0524** [qkaren/Counterfactual-StoryRW#5]
The version 0.2.1 of texar installed from github may not have the module 'reduce_with_weights' in 'texar.utils' with the attribute error when called by rewriting_main.py.
![image](https://user-images.githubusercontent.com/24388932/66740517-fb060100-eea5-11e9-86d7-c2ffee678626.png)

**Comment by qkaren** [comment]
The particular version of Texar used in this code is uploaded under [`third_party/`](https://github.com/qkaren/Counterfactual-StoryRW/tree/master/third_party/texar)

**Comment by HappyGu0524** [comment]
Is the data used for generation included in the repositories? It seems like raw sentences rather than the TimeTravel dataset.
![image](https://user-images.githubusercontent.com/24388932/67616018-325da180-f806-11e9-97f8-7124b92e389a.png)

 Or how can I get the 'train.tf_record'?

**Comment by qkaren** [comment]
Thanks for the question! You'll need to run `prepare_data_rewriting.py` to process and transform the raw text data into TFRecord format. I've updated the README to [reflect this](https://github.com/qkaren/Counterfactual-StoryRW#code).

**Comment by sy2yp** [comment]
Hi, 
I have a question about prepare_data_rewriting.py
It looks like the raw data should be .txt
Do you simply rewrite the .json files (keys and values) as text or keep the sentences (values) only?
Thanks!
