### ISSUE TITLE
Something wrong with the texar.modules.TransformerDecoder

### ISSUE THREAD

**Issue by li3cmz** [qkaren/Counterfactual-StoryRW#6]
https://github.com/qkaren/Counterfactual-StoryRW/blob/fc7a96ed0eadcaf6917601a54e1c278dff0fee76/rewriting_main.py#L302

It seems that texar release version now can only support the **context** with shape of [batch_size, length].

The description of TransformerDecoder's **context** in [texar document](https://texar.readthedocs.io/en/latest/code/modules.html#transformerdecoder) is as follows:

**context (optional)** – An int Tensor of shape [batch_size, length], containing the starting tokens for decoding. If context is set, the start_tokens will be ignored.

**Comment by qkaren** [comment]
The particular Texar version used in this code is uploaded under `third_party/`
