### ISSUE TITLE
AttributeError: module 'tensorflow.python.layers.layers' has no attribute 'Layer'

### ISSUE THREAD

**Issue by Hannabrahman** [qkaren/Counterfactual-StoryRW#7]
Hi, Thanks for the nice code.
I am getting the following error when trying to preprocess data. (Note that I downloaded TimeTravel data and put it in the TimeTravel folder)
Does it have something to do with a tf version? Does the code need a specific tf version?

```
Counterfactual-StoryRW$ python prepare_data_rewriting.py --data_dir=TimeTravel
Traceback (most recent call last):
  File "prepare_data_rewriting.py", line 22, in <module>
    import texar as tx
  File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/__init__.py", line 29, in <module>
    from texar import modules
  File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/modules/__init__.py", line 24, in <module>
    from texar.modules.networks import *
  File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/modules/networks/__init__.py", line 24, in <module>
    from texar.modules.networks.network_base import *
  File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/modules/networks/network_base.py", line 26, in <module>
    from texar.core.layers import get_layer
  File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/core/__init__.py", line 24, in <module>
    from texar.core.layers import *
  File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/core/layers.py", line 629, in <module>
    class _ReducePooling1D(tf.layers.Layer):
AttributeError: module 'tensorflow.python.layers.layers' has no attribute 'Layer'
```

**Comment by Hannabrahman** [comment]
> Hi, Thanks for the nice code.
> I am getting the following error when trying to preprocess data. (Note that I downloaded TimeTravel data and put it in the TimeTravel folder)
> Does it have something to do with a tf version? Does the code need a specific tf version?
> 
> ```
> Counterfactual-StoryRW$ python prepare_data_rewriting.py --data_dir=TimeTravel
> Traceback (most recent call last):
>   File "prepare_data_rewriting.py", line 22, in <module>
>     import texar as tx
>   File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/__init__.py", line 29, in <module>
>     from texar import modules
>   File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/modules/__init__.py", line 24, in <module>
>     from texar.modules.networks import *
>   File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/modules/networks/__init__.py", line 24, in <module>
>     from texar.modules.networks.network_base import *
>   File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/modules/networks/network_base.py", line 26, in <module>
>     from texar.core.layers import get_layer
>   File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/core/__init__.py", line 24, in <module>
>     from texar.core.layers import *
>   File "/home/hannah/Counterfactual-StoryRW/third_party/texar/texar/core/layers.py", line 629, in <module>
>     class _ReducePooling1D(tf.layers.Layer):
> AttributeError: module 'tensorflow.python.layers.layers' has no attribute 'Layer'
> ```

Actually if was a tensorflow version error.

**Comment by czha5168** [comment]
Hi fabrahman, Could you please share the tensorflow version that you used to fix this error? Cheers!

**Comment by fabrahman** [comment]
> Hi fabrahman, Could you please share the tensorflow version that you used to fix this error? Cheers!

Hi, I think when I used tf version `1.14.0` the problem resolved. Hope that helps.

**Comment by czha5168** [comment]
Thanks mate!
________________________________

**Comment by ccyun1127** [comment]
> Oh should I create train_x1.txt and other txt files from the TimeTravel json files? And depending on what training scheme, should I concatenate them? for example for supervised training, I do the following for train_supervised_small.json: full_roc_story + [s] +premise+ counter + edited Basically, x1 = premise, x2=initial, xx2=counterfactual, y=original_ending and yy=edited_ending. And you save them in separate text files, right?

Hi fabrahman, I have the same problem, but I still don't understand what's the train_x1.txt should be like.
Cloud you please provide the train_x1.txt and other txt files that you create?
