### ISSUE TITLE
What is the contrastive loss?

### ISSUE THREAD

**Issue by ehsan-soe** [qkaren/Counterfactual-StoryRW#9]
Hi,

What is the contrastive loss defined [here](https://github.com/qkaren/Counterfactual-StoryRW/blob/d16f8fb5ac7b829ad39d6c2afec4ab83dd1c0975/rewriting_main.py#L284). Is it used in decoding?

**Comment by qkaren** [comment]
This loss is not used in training. They can be deleted.
